version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postback_mvp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postback_mvp
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4
    container_name: postback_mvp_adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  dbdata:
